### PR TITLE
Retrigger build for schema bug analysis

### PR DESCRIPTION
**Pull request by fcollonval**
Checklist
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Retrigger the build to analyse the issue reported there:
https://github.com/hadim/jupyter-archive/issues/29

### CODE REVIEW

**Comment by fcollonval** [comment]
@conda-forge-admin, please rerender

**Comment by hadim** [comment]
Here is the only `archive.json` I found in the build logs:

```
  adding 'jupyter_archive-0.5.4.data/data/etc/jupyter/jupyter_notebook_config.d/jupyter_archive.json'
```

**Comment by hadim** [comment]
@fcollonval: conda-forge devs prefer people to open a PR from a fork and from the conda-forge repo.

**Comment by hadim** [comment]
I close here. See https://github.com/conda-forge/jupyter-archive-feedstock/pull/4

**Pull request closed without merging**
